### ISSUE TITLE
[low] applespi.h relies on transitive BIT() include — should include <linux/bitops.h>

### ISSUE THREAD

**Issue by ronnyf** [ronnyf/macbook12-spi-driver#109]
**Location:** `applespi.h:13-20`
**Category:** Header hygiene

## Problem

`applespi.h` uses `BIT(0)` … `BIT(12)` in an enum but does not include `<linux/bitops.h>` (or `<linux/bits.h>` on newer kernels). It also has no other includes at all.

The header compiles today only because every consumer (`applespi.c`, `applespi_trace.h` via `applespi.c`) includes something else first that transitively pulls in `BIT()`. Any reordering or new consumer breaks compilation with `error: implicit declaration of function 'BIT'`.

Note: kernel header convention is that `include/linux/<x>.h` headers are standalone-includable.

## Impact

Latent build breakage on include reordering or any new consumer. Today: works.

## Suggested fix

```c
#ifndef _APPLESPI_H_
#define _APPLESPI_H_

#include <linux/bitops.h>   /* for BIT() — works on 4.14+; <linux/bits.h> on 4.19+ */

enum applespi_evt_type { ... };
```

Same hygiene improvement applies to `apple-ibridge.h` (declares `bool` without `<linux/types.h>`).
